/********************************************************************/
/*                                                                  */
/*                 Generated by Build Info Generator                */
/*                      (C) 2021 Marc Schöndorf                     */
/*                                                                  */
/*  All modifications to this file                                  */
/*  will be replaced on next run.                                   */
/********************************************************************/

#pragma once

// To disable updates to this file, set "BUILD_INFO_GENERATOR_PAUSE" to "1".
#define BUILD_INFO_GENERATOR_PAUSE 0

// Generated info
#define BUILD_INFO_GENERATOR_BUILD_NUMBER 0

#define BUILD_INFO_GENERATOR_DAY 16
#define BUILD_INFO_GENERATOR_MONTH 08
#define BUILD_INFO_GENERATOR_YEAR 2021

#define BUILD_INFO_GENERATOR_HOUR 13
#define BUILD_INFO_GENERATOR_MINUTE 13
#define BUILD_INFO_GENERATOR_SECOND 03

/********************** End of generated file **********************/