/********************************************************************/
/*                                                                  */
/*                 Generated by Build Info Generator                */
/*                                                                  */
/*  All modifications to this file                                  */
/*  will be replaced on next run.                                   */
/********************************************************************/

#pragma once

// To disable updates to this file, set "BUILD_INFO_GENERATOR_PAUSE" to "1".
#define BUILD_INFO_GENERATOR_PAUSE 0

// Generated info
#define BUILD_INFO_GENERATOR_BUILD_NUMBER 2

#define BUILD_INFO_GENERATOR_DAY 17
#define BUILD_INFO_GENERATOR_MONTH 08
#define BUILD_INFO_GENERATOR_YEAR 2021
#define BUILD_INFO_GENERATOR_DATE_STR "17.08.2021"

#define BUILD_INFO_GENERATOR_HOUR 06
#define BUILD_INFO_GENERATOR_MINUTE 49
#define BUILD_INFO_GENERATOR_SECOND 02

#define BUILD_INFO_GENERATOR_TIME_STR "06:49:02"

/********************** End of generated file **********************/